### ISSUE TITLE
StringIO (Python 3)

### ISSUE THREAD

**Issue by michipili** [russell/sphinxcontrib-cldomain#12]
On my system in a cl-git working copy I use as an example, running 

```
sphinx-build -b html -E . html    
```

fails with the following message

```
Running Sphinx v1.7.5

Extension error:
Could not import extension sphinxcontrib.cldomain (exception: No module named 'StringIO')
```

My understanding is that this is a general little incompatibility between Python 2 and 3, yet I am not totally sure.

My system is Mac OS-X Running MacPorts,

```
% uname -a
Darwin oscar.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
% python --version
Python 3.6.5
% pip --version
pip 9.0.3 from /Users/michael/Workshop/cl-git/michipili/lib/python3.6/site-packages (python 3.6)
```

**Comment by svetlyak40wt** [comment]
You can replace it with `six.StringIO` and it will work both in 2 and 3 pythons.

https://pythonhosted.org/six/#six.StringIO

**Comment by michipili** [comment]
What do you mean by replace? Patching the sphinxcontrib-cldomain code to use that specific module?

**Comment by svetlyak40wt** [comment]
Exactly.

**Comment by michipili** [comment]
Thanks!
