### ISSUE TITLE
Bootstrap error

### ISSUE THREAD

**Issue by mmontone** [russell/sphinxcontrib-cldomain#2]
I'm having this error, even though I'm not using the bootstrap theme, and have sphinx-bootstrap-theme installed.

marian@gimli ~/src/lisp/cldm/doc/manual $ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.2.3

Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/cldomain.py", line 1049, in import_class
    return getattr(m, classname)
AttributeError: 'module' object has no attribute 'BootstrapTranslator'
The full traceback has been saved in /tmp/sphinx-err-cELH1u.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1

What could be the problem?

**Comment by mmontone** [comment]
The problem seems to go away if I comment the BootstrapTranslator lines, but then I run into this:

Exception occurred:
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/usr/bin/cl-launch', '--lisp', 'sbcl ecl', '--init', '\n#-quicklisp\n(let ((quicklisp-init (merge-pathnames (make-pathname :name "setup"\n                                                      :type "lisp")\n                                       (concatenate \'string (asdf/os:getenv "QUICKLISP")\n                                                    "/"))))\n  (if (probe-file quicklisp-init)\n      (load quicklisp-init)\n      (error "Can\'t Find Quicklisp at ~a~%" quicklisp-init)))\n', '--init', '\n(push (pathname (concatenate \'string (asdf/os:getenv "CLDOMAIN") "/"))\n                             asdf:*central-registry*)\n', '--init', '(asdf:initialize-source-registry)', '--init', "(require 'quicklisp)", '--init', "\n(let ((*standard-output* *error-output*))\n  (quicklisp:quickload 'sphinxcontrib.cldomain))\n", '--init', '(sphinxcontrib.cldomain:main)', '--', '--package', 'CLDM', '--system', 'cldm', '--path', u'/home/marian/src/lisp/cldm/doc/manual/../../']' returned non-zero exit status 99
The full traceback has been saved in /tmp/sphinx-err-uL28Kj.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1

**Comment by mmontone** [comment]
It is a pity I don't know how to visualize the command output to check what's the problem.

**Comment by mmontone** [comment]
Ok. This last error is an issue with my package, but I think the Bootstrap problem remains

**Comment by mmontone** [comment]
Ok. FYI, there are some issues with cl-launch and some lisp packages that change the readtable, like cxml. See: http://blog.gmane.org/gmane.lisp.lib.cxml.devel/month=20140801

So, the documentation build will fail for some lisp packages, depending on what they depend on. I've fixed the issue appending (setf *readtable* (copy-readtable nil)) to the quickload command in cldomain.py, but I guess it is still a hack.

**Comment by russell** [comment]
Interesting.  I'll look at adding it in the short term until it's fixed in ASDF.

Thanks for the bug report!

**Comment by mmontone** [comment]
Ok. But remember that the Bootstrap issue remains! :)

**Comment by russell** [comment]
Oh shoot, yeah i see it. OK cool ta.
