### ISSUE TITLE
CLON system name

### ISSUE THREAD

**Issue by mmontone** [russell/sphinxcontrib-cldomain#3]
Didier Verna's CLON system name seems to have changed in lastest Quicklisp dist.

Instead of com.dvlsoft.clon, it is called net.didierverna.clon now. Should be changed in package.lisp and sphinxcontrib.cldomain.asd

**Comment by russell** [comment]
Thanks for the heads up I'll fix it shortly.

**Comment by russell** [comment]
Sorry about taking so long to fix that :(
