### ISSUE TITLE
genericFunction error

### ISSUE THREAD

**Issue by liamh** [russell/sphinxcontrib-cldomain#6]
Docstrings for generic functions do not get processed when the function is identified as a regular function. In cldomain.py, there is "genericFunction" but using this produces an error:

```
 /home/healy/mathematics/antik/documentation/source/optimize.rst:5: ERROR: Unknown directive type "cl:genericFunction".
```

**Comment by russell** [comment]
this has been fixed in master, there is an all new generic rendering system that is much better
