### ISSUE TITLE
PDF has wrong arglist

### ISSUE THREAD

**Issue by liamh** [russell/sphinxcontrib-cldomain#7]
When generating PDF, the arglist is wrong; it is correct in HTML. For example, for

```
(defun set-reader (&optional (readtable t) (default-float 'double-float))
  "If readtable is true,..."
  ...)
```

the HTML is generated correctly as

```
 function (set-reader &optional (readtable t) (default-float (quote double-float)))

 If readtable is true,...
```

but the PDF comes out

```
 function (set-reader&optional)readtable t
   default-floatquote double-float If readtable is true,..
```

**Comment by russell** [comment]
Hey, sorry for taking so long to get to this, but I have fixed this bug on master, and it will be included in the next release
