### ISSUE TITLE
Support for macros, classes, and conditions.

### ISSUE THREAD

**Issue by liamh** [russell/sphinxcontrib-cldomain#8]
There does not appear to be any support for macros, classes, or conditions. I have used function for macros, but then it is not correctly labeled.

**Comment by svetlyak40wt** [comment]
Please, read the docs.

Macroses: http://cldomain.russellsim.org/#macro
Classes: http://cldomain.russellsim.org/#class

But seems, conditions are not supported. Probably, because they are classes?

**Comment by russell** [comment]
macros are indeed supported.

class support is still crap, i'm going to close down this tracker. i'll be working on class support next, it's the only major feature i can think that remains

this project is moving here https://sr.ht/~rsl/sphinxcontrib-cldomain/
